import type { NotificationEventDefinition } from './types';

export const notificationEvents: NotificationEventDefinition[] = [
  {
    id: 'inventory.low-stock',
    label: 'Varianta má nízkou zásobu',
    description: 'Skladová zásoba klesla pod definované minimum nebo bezpečnostní množství.',
    severity: 'warning',
    module: 'inventory',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'email'],
    sampleLog: 'Varianta #10230 (Velká vůně) klesla pod minimální zásobu (3 ks).',
    tags: ['zásoby', 'minima'],
  },
  {
    id: 'inventory.out-of-stock',
    label: 'Varianta je vyprodaná',
    description: 'Dostupná zásoba varianty nebo produktu spadla na nulu.',
    severity: 'error',
    module: 'inventory',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'email', 'slack'],
    sampleLog: 'Produkt "Dárkový box Citrus" je vyprodaný na všech skladech.',
    tags: ['zásoby'],
  },
  {
    id: 'inventory.restock',
    label: 'Zboží je opět skladem',
    description: 'Zásoba produktu se doplnila nad prah pro oznámení.',
    severity: 'success',
    module: 'inventory',
    defaultEnabled: true,
    recommendedChannels: ['ui'],
    sampleLog: 'Varianta #9981 (Tester kolekce) byla doplněna na 45 ks.',
    tags: ['zásoby', 'back-in-stock'],
  },
  {
    id: 'inventory.slow-mover',
    label: 'Pomalý pohyb zásob',
    description: 'Zásoba se nehýbe déle než definovaný počet dní nebo hrozí expirace.',
    severity: 'info',
    module: 'inventory',
    defaultEnabled: false,
    recommendedChannels: ['ui'],
    sampleLog: 'Varianta #1124 (Vánoční svíčka) neměla prodej 28 dní.',
    tags: ['zásoby', 'slow-mover'],
  },
  {
    id: 'orders.high-value',
    label: 'Nová vysoká objednávka',
    description: 'Byla přijata objednávka nad sledovaný finanční limit.',
    severity: 'success',
    module: 'orders',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'slack'],
    sampleLog: 'Objednávka #20240318045 v hodnotě 18 900 Kč čeká na platbu.',
    tags: ['objednávky'],
  },
  {
    id: 'orders.status-changed',
    label: 'Změna stavu objednávky',
    description: 'Objednávka změnila stav na sledovaný status (zaplaceno, expedováno, vráceno).',
    severity: 'info',
    module: 'orders',
    defaultEnabled: false,
    recommendedChannels: ['ui'],
    sampleLog: 'Objednávka #20240317011 změnila stav na "Zaplaceno".',
    tags: ['objednávky', 'workflow'],
  },
  {
    id: 'orders.import-failed',
    label: 'Chyba importu objednávek',
    description: 'Snapshot objednávek nebo synchronizace ze Shoptetu selhala.',
    severity: 'error',
    module: 'orders',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'slack'],
    sampleLog: 'Import objednávek pro shop #12 selhal: HTTP 500 z Shoptetu.',
    tags: ['shoptet', 'snapshot'],
  },
  {
    id: 'orders.volume-spike',
    label: 'Nárůst počtu objednávek',
    description: 'Byl zjištěn neobvykle vysoký počet objednávek oproti průměru.',
    severity: 'warning',
    module: 'orders',
    defaultEnabled: false,
    recommendedChannels: ['ui'],
    sampleLog: 'Objednávky za poslední hodinu jsou o 320 % vyšší než běžně.',
    tags: ['objednávky', 'anomaly'],
  },
  {
    id: 'customers.vip-created',
    label: 'Nový VIP zákazník',
    description: 'Zákazník překročil definovanou CLV nebo byl ručně označen jako VIP.',
    severity: 'success',
    module: 'customers',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'email'],
    sampleLog: 'Zákazník Jana Malá dosáhla CLV 35 400 Kč a byla označena jako VIP.',
    tags: ['zákazníci', 'vip'],
  },
  {
    id: 'customers.metrics-ready',
    label: 'Přepočet metrik dokončen',
    description: 'Byl úspěšně dokončen dávkový přepočet zákaznických metrik.',
    severity: 'info',
    module: 'customers',
    defaultEnabled: true,
    recommendedChannels: ['ui'],
    sampleLog: 'Přepočet metrik zákazníků dokončen (zpracováno 4 812 záznamů).',
    tags: ['zákazníci', 'metriky'],
  },
  {
    id: 'customers.backfill-issue',
    label: 'Chyba párování zákazníka',
    description: 'Backfill nebo sync zákazníků narazil na duplicitní e-mail nebo chybějící souhlas.',
    severity: 'warning',
    module: 'customers',
    defaultEnabled: true,
    recommendedChannels: ['ui'],
    sampleLog: 'Objednávka #20240316021 nelze spárovat: duplicitní e-mail customer@example.com.',
    tags: ['zákazníci', 'integrace'],
  },
  {
    id: 'pim.translation-assigned',
    label: 'Nový překladový úkol',
    description: 'Překlad produktu nebo kategorie byl přiřazen uživateli.',
    severity: 'info',
    module: 'pim',
    defaultEnabled: true,
    recommendedChannels: ['ui'],
    sampleLog: 'Úkol "Překlad produktu 5821 – EN" byl přiřazen uživateli Jana.',
    tags: ['pim', 'workflow'],
  },
  {
    id: 'pim.translation-approved',
    label: 'Překlad schválen',
    description: 'Překlad produktu/kategorie byl schválen a čeká na export.',
    severity: 'success',
    module: 'pim',
    defaultEnabled: false,
    recommendedChannels: ['ui'],
    sampleLog: 'Překlad produktu #5821 byl schválen týmem QC.',
    tags: ['pim', 'workflow'],
  },
  {
    id: 'pim.push-failed',
    label: 'Push překladu do Shoptetu selhal',
    description: 'Během exportu do Shoptetu došlo k chybě (validace dat / API).',
    severity: 'error',
    module: 'pim',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'slack'],
    sampleLog: 'Push kategorie "Doplňky" selhal: neplatný HTML obsah.',
    tags: ['shoptet', 'pim'],
  },
  {
    id: 'shoptet.snapshot-success',
    label: 'Snapshot dokončen',
    description: 'Snapshot Shoptetu byl úspěšně stažen a zpracován.',
    severity: 'success',
    module: 'shoptet',
    defaultEnabled: true,
    recommendedChannels: ['ui'],
    sampleLog: 'Snapshot produktů pro shop #9 zpracován – 12 431 řádků.',
    tags: ['shoptet', 'snapshot'],
  },
  {
    id: 'shoptet.snapshot-failed',
    label: 'Snapshot selhal',
    description: 'Shoptet job skončil ve stavu failed nebo se nepodařilo stáhnout soubor.',
    severity: 'error',
    module: 'shoptet',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'slack'],
    sampleLog: 'Snapshot objednávek pro shop #4 selhal: job vrací stav cancelled.',
    tags: ['shoptet', 'snapshot'],
  },
  {
    id: 'shoptet.token-expiring',
    label: 'Token se blíží expiraci',
    description: 'API token Shoptetu expiruje do 7 dnů.',
    severity: 'warning',
    module: 'shoptet',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'email'],
    sampleLog: 'Token pro shop parfumery.cz expiruje za 5 dnů.',
    tags: ['shoptet', 'token'],
  },
  {
    id: 'shoptet.master-product-added',
    label: 'Master shop přidal produkt',
    description: 'V master katalogu se objevil nový produkt nebo varianta.',
    severity: 'info',
    module: 'shoptet',
    defaultEnabled: true,
    recommendedChannels: ['ui'],
    sampleLog: 'Master shop přidal produkt "Jarní kolekce 2024" (SKU SPRING24-01).',
    tags: ['produkty', 'shoptet'],
  },
  {
    id: 'analytics.digest-ready',
    label: 'Digest report je připraven',
    description: 'Denní nebo týdenní report byl vygenerován a čeká na přečtení.',
    severity: 'info',
    module: 'analytics',
    defaultEnabled: false,
    recommendedChannels: ['ui', 'email'],
    sampleLog: 'Týdenní přehled výkonu za 11.–17. března je připraven ke stažení.',
    tags: ['reporty'],
  },
  {
    id: 'system.job-failed',
    label: 'Queue job selhal',
    description: 'Job ve frontě skončil chybou i po retry pokusech.',
    severity: 'error',
    module: 'system',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'slack'],
    sampleLog: 'Job ProcessShoptetSnapshot (shop #3) selhal: SQLSTATE[23505] duplicate key.',
    tags: ['queue', 'monitoring'],
  },
  {
    id: 'system.queue-stalled',
    label: 'Fronta je zahlcená',
    description: 'Čeká více než X jobů nebo žádný job neběží delší dobu.',
    severity: 'warning',
    module: 'system',
    defaultEnabled: true,
    recommendedChannels: ['ui', 'slack'],
    sampleLog: 'Fronta snapshots má 48 čekajících jobů, poslední běh před 24 minutami.',
    tags: ['queue', 'monitoring'],
  },
  {
    id: 'system.release-deployed',
    label: 'Nová verze nasazena',
    description: 'Do produkce byla nasazena nová verze aplikace.',
    severity: 'success',
    module: 'system',
    defaultEnabled: false,
    recommendedChannels: ['ui'],
    sampleLog: 'Release 2024.03.18 byl nasazen – změny: notifikační centrum, AI plugin fix.',
    tags: ['release'],
  },
];

export const notificationEventMap = notificationEvents.reduce<
  Record<NotificationEventDefinition['id'], NotificationEventDefinition>
>(
  (acc, event) => {
    acc[event.id] = event;
    return acc;
  },
  {} as Record<NotificationEventDefinition['id'], NotificationEventDefinition>
);
